/*
 * This file is generated by jOOQ.
 */
package com.demo.sb_jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 用户信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -168766240;

    private String userId;
    private String name;
    private String intro;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.name = value.name;
        this.intro = value.intro;
    }

    public User(
        String userId,
        String name,
        String intro
    ) {
        this.userId = userId;
        this.name = name;
        this.intro = intro;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIntro() {
        return this.intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(intro);

        sb.append(")");
        return sb.toString();
    }
}
