/*
 * This file is generated by jOOQ.
 */
package com.demo.sb_jooq.generator;


import com.demo.sb_jooq.generator.tables.FlywaySchemaHistory;
import com.demo.sb_jooq.generator.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpringbootJooq extends SchemaImpl {

    private static final long serialVersionUID = 910624316;

    /**
     * The reference instance of <code>springboot_jooq</code>
     */
    public static final SpringbootJooq SPRINGBOOT_JOOQ = new SpringbootJooq();

    /**
     * The table <code>springboot_jooq.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.demo.sb_jooq.generator.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 用户信息
     */
    public final User USER = com.demo.sb_jooq.generator.tables.User.USER;

    /**
     * No further instances allowed
     */
    private SpringbootJooq() {
        super("springboot_jooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            User.USER);
    }
}
