/*
 * This file is generated by jOOQ.
 */
package com.demo.sb_jooq.generator;


import com.demo.sb_jooq.generator.tables.FlywaySchemaHistory;
import com.demo.sb_jooq.generator.tables.User;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in springboot_jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>springboot_jooq.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 用户信息
     */
    public static final User USER = User.USER;
}
